// Generated by CoffeeScript 1.8.0
(function() {
  var VERBOSE, coffee_reactify, fs, metaserve_js_browserify, through, unliterate;

  fs = require('fs');

  coffee_reactify = require('coffee-reactify');

  metaserve_js_browserify = require('metaserve-js-browserify');

  through = require('through');

  require('node-cjsx').transform();

  VERBOSE = process.env.METASERVE_VERBOSE != null;

  unliterate = function(file) {
    var data, end, write;
    data = '';
    write = function(buf) {
      data += buf;
    };
    end = function() {
      var lines;
      lines = data.split('\n').filter(function(line) {
        return line.indexOf('    ') === 0;
      });
      data = lines.join('\n');
      this.queue(data);
      this.queue(null);
    };
    return through(write, end);
  };

  module.exports = {
    ext: 'litcoffee',
    default_config: {
      content_type: 'application/javascript',
      browserify: {
        extensions: ['.coffee', '.litcoffee']
      },
      browserify_shim: false,
      uglify: false
    },
    compile: function(filename, config, context, cb) {
      if (VERBOSE) {
        console.log('[LitCoffeeReactifyCompiler.compile]', filename, config);
      }
      config.beforeBundle = function(bundler) {
        bundler = bundler.transform(unliterate).transform(coffee_reactify);
        return bundler;
      };
      return metaserve_js_browserify.compile(filename, config, context, cb);
    }
  };

}).call(this);
