// Generated by CoffeeScript 1.8.0
(function() {
  var VERBOSE, coffee_reactify, fs, metaserve_js_browserify;

  fs = require('fs');

  coffee_reactify = require('coffee-reactify');

  metaserve_js_browserify = require('metaserve-js-browserify');

  require('node-cjsx').transform();

  VERBOSE = process.env.METASERVE_VERBOSE != null;

  module.exports = {
    ext: 'litcoffee',
    default_config: {
      content_type: 'application/javascript',
      browserify: {
        extensions: ['.coffee', '.litcoffee'],
        literate: true
      },
      browserify_shim: false,
      uglify: false
    },
    compile: function(filename, config, context, cb) {
      if (VERBOSE) {
        console.log('[LitCoffeeReactifyCompiler.compile]', filename, config);
      }
      config.beforeBundle = function(bundler) {
        bundler = bundler.transform(coffee_reactify);
        return bundler;
      };
      return metaserve_js_browserify.compile(filename, config, context, cb);
    }
  };

}).call(this);
